sudo: false
language: node_js
node_js:
  - "6.10"
branches:
  only:
  - master
cache:
  directories:
    - node_modules
before_install:
  - npm install -g yarn hexo hexo-cli
before_script:
  - git config --global user.name 'logzh'
  - git config --global user.email 'zjhcug@qq.com'
  - sed -i'' "s~git@github.com:logzh/logzh.github.io.git~https://${REPO_TOKEN}:x-oauth-basic@github.com/logzh/logzh.github.io.git~" _config.yml
install:
  - yarn install
script:
  - hexo clean
  - hexo generate
after_success:
  - hexo deploy